# from django.db import models
# from .workoutSessions import WorkoutSession
# from .exerciseLibrary import ExerciseLibrary
# from django.core.validators import MinValueValidator, MaxValueValidator


# class WorkoutSet(models.Model):
#     """
#     Granular data for every set performed.
#     CRITICAL for 'Vision Form Tracker' integration.
#     """
#     session = models.ForeignKey(WorkoutSession, on_delete=models.CASCADE, related_name='sets')
#     exercise = models.ForeignKey(ExerciseLibrary, on_delete=models.PROTECT)
#     setOrder = models.PositiveIntegerField()
    
#     weight_kg = models.DecimalField(max_digits=5, decimal_places=2)
#     reps = models.PositiveIntegerField()
#     rpe = models.PositiveIntegerField(validators=[MinValueValidator(1), MaxValueValidator(10)], null=True)
    
#     # VISION CV INTEGRATION
#     # vision_form_score = models.IntegerField(
#     #     null=True, blank=True,
#     #     validators=[MinValueValidator(0), MaxValueValidator(100)],
#     #     help_text="Score (0-100) generated by the Computer Vision module"
#     # )
#     # vision_feedback = models.TextField(blank=True, help_text="Specific form errors detected by CV (e.g., 'Knees caving in')")

#     class Meta:
#         ordering = ['setOrder']
