# Generated by Django 5.1.4 on 2025-12-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appusers',
            old_name='height_cm',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='appusers',
            old_name='primary_goal',
            new_name='primaryGoal',
        ),
        migrations.RenameField(
            model_name='appusers',
            old_name='weight_kg',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='appusers',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='appusers',
            name='injury_history',
        ),
        migrations.AddField(
            model_name='appusers',
            name='activityLevel',
            field=models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Lightly Active'), ('moderate', 'Moderately Active'), ('very', 'Very Active'), ('extreme', 'Extremely Active')], default='moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='appusers',
            name='country',
            field=models.CharField(default='India', max_length=50),
        ),
        migrations.AddField(
            model_name='appusers',
            name='firstName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='appusers',
            name='lastName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='appusers',
            name='protocol',
            field=models.CharField(default='Generate', max_length=50),
        ),
    ]
