# Generated by Django 5.1.4 on 2025-12-14 13:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_height_cm_appusers_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('current_intake_ml', models.PositiveIntegerField(default=0)),
                ('daily_goal_ml', models.PositiveIntegerField(default=3000)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_logs', to='base.appusers')),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
